name: Release

defaults:
  run:
    shell: bash

on:
  push:
    branches-ignore:
      - '**'
    tags:
      - 'v*.*.*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'true'

      - name: Fetch all tags
        run: git fetch --force --tags

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: setup release environment
        run: |-
          echo '${{secrets.DOCKERHUB_USERNAME}}:${{secrets.DOCKERHUB_TOKEN}}:docker.io' > .docker-creds
          echo 'DOCKER_CREDS_FILE=.docker-creds'                                        > .release-env
          echo 'GITHUB_TOKEN=${{secrets.GITHUB_TOKEN}}'                                >> .release-env

      - name: release dry run
        run: make release-dry-run

      - name: release publish
        run: |-
          sudo rm -rf dist
          make release
